"""
test_notification_service.py — Full test suite for NotificationService.
Generated by Spec2Code Stage 4 (Test Generation Agent).
REQs covered: REQ-008, REQ-017
"""
import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.services.notification_service import NotificationService


@pytest.fixture
def svc():
    return NotificationService()


# ── REQ-008: Order Confirmation Email ────────────────────────────────────────

def test_send_order_confirmation_email(svc):
    """REQ-008: send_order_confirmation returns a sent=True confirmation dict."""
    result = svc.send_order_confirmation("alice@example.com", "ORD-ABC123", 109.97)
    assert result is not None
    assert result["sent"] is True
    assert result["type"] == "order_confirmation"
    assert result["order_id"] == "ORD-ABC123"
    assert result["recipient"] == "alice@example.com"


def test_send_order_confirmation_includes_total(svc):
    """REQ-008: Confirmation email record includes total_amount."""
    result = svc.send_order_confirmation("bob@example.com", "ORD-DEF456", 59.99)
    assert result["total_amount"] == 59.99


# ── REQ-017: Cancellation Confirmation Email ─────────────────────────────────

def test_send_cancellation_email_on_cancel(svc):
    """REQ-017: send_cancellation_email returns sent=True with order_id and refund_amount."""
    result = svc.send_cancellation_email("alice@example.com", "ORD-ABC123", 109.97)
    assert result is not None
    assert result["sent"] is True
    assert result["type"] == "cancellation_confirmation"
    assert result["order_id"] == "ORD-ABC123"
    assert result["refund_amount"] == 109.97


def test_send_cancellation_email_includes_recipient(svc):
    """REQ-017: Cancellation email record includes recipient address."""
    result = svc.send_cancellation_email("carol@example.com", "ORD-GHI789", 29.99)
    assert result["recipient"] == "carol@example.com"


def test_send_cancellation_email_returns_dict(svc):
    """REQ-017: Return value must be a dict, not None."""
    result = svc.send_cancellation_email("dave@example.com", "ORD-JKL012", 149.50)
    assert isinstance(result, dict)
