"""
test_payment_service.py — Full test suite for PaymentService.
Generated by Spec2Code Stage 4 (Test Generation Agent).
REQs covered: REQ-009, REQ-014
"""
import pytest
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.services.payment_service import PaymentService


@pytest.fixture
def svc():
    service = PaymentService()
    service._transactions = {}
    return service


# ── REQ-009: Payment Processing ──────────────────────────────────────────────

def test_charge_payment_success(svc):
    """REQ-009: charge_payment returns a transaction record with a transaction_id."""
    result = svc.charge_payment("USER-001", 109.97, "CARD-VISA")
    assert result is not None
    assert result["transaction_id"].startswith("TXN-")
    assert result["status"] == "CHARGED"


def test_charge_payment_records_transaction(svc):
    """REQ-009: Charged transaction is stored and retrievable."""
    result = svc.charge_payment("USER-001", 49.99, "CARD-MASTERCARD")
    txn_id = result["transaction_id"]
    assert txn_id in svc._transactions
    assert svc._transactions[txn_id]["amount"] == 49.99


def test_charge_payment_correct_amount(svc):
    """REQ-009: Charged amount matches the requested amount."""
    result = svc.charge_payment("USER-002", 199.00, "CARD-AMEX")
    assert result["amount"] == 199.00


# ── REQ-014: Payment Refund ──────────────────────────────────────────────────

def test_refund_on_cancellation(svc):
    """REQ-014: refund_payment returns a refund record with a refund_id."""
    charge = svc.charge_payment("USER-001", 109.97, "CARD-VISA")
    refund = svc.refund_payment(charge["transaction_id"], 109.97)
    assert refund is not None
    assert refund["refund_id"].startswith("REF-")
    assert refund["status"] == "REFUNDED"
    assert refund["amount"] == 109.97


def test_refund_marks_original_transaction(svc):
    """REQ-014: Original transaction status is updated to REFUNDED."""
    charge = svc.charge_payment("USER-001", 75.00, "CARD-VISA")
    svc.refund_payment(charge["transaction_id"], 75.00)
    assert svc._transactions[charge["transaction_id"]]["status"] == "REFUNDED"


def test_refund_unknown_transaction(svc):
    """REQ-014: Refunding unknown transaction returns success=False."""
    result = svc.refund_payment("TXN-UNKNOWN", 50.00)
    assert result["success"] is False
