"""
test_order_service.py — Full test suite for OrderService.
Generated by Spec2Code Stage 4 (Test Generation Agent).
REQs covered: REQ-007, REQ-011, REQ-012, REQ-013, REQ-016, REQ-019
"""
import pytest
import sys
import os

# Ensure the stub project root is on sys.path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.services.order_service import OrderService
from app.models.order import OrderItem, OrderStatus


@pytest.fixture
def svc():
    service = OrderService()
    service._orders = {}  # fresh state per test
    return service


@pytest.fixture
def sample_items():
    return [
        OrderItem(product_id="PROD-001", product_name="Wireless Headphones", quantity=2, unit_price=49.99),
        OrderItem(product_id="PROD-002", product_name="USB-C Cable", quantity=1, unit_price=9.99),
    ]


# ── REQ-007: Place Order ─────────────────────────────────────────────────────

def test_place_order_creates_order(svc, sample_items):
    """REQ-007: Placing an order returns an Order object with an order_id."""
    order = svc.place_order("USER-001", sample_items)
    assert order is not None
    assert order.order_id.startswith("ORD-")
    assert order.user_id == "USER-001"
    assert len(order.items) == 2


def test_place_order_sets_pending_status(svc, sample_items):
    """REQ-007: New orders must start in PENDING status."""
    order = svc.place_order("USER-001", sample_items)
    assert order.status == OrderStatus.PENDING


def test_place_order_calculates_total(svc, sample_items):
    """REQ-007: Order total must equal sum of item prices × quantities."""
    order = svc.place_order("USER-001", sample_items)
    expected = round(2 * 49.99 + 1 * 9.99, 2)
    assert order.total_amount == expected


# ── REQ-011: Order Status ────────────────────────────────────────────────────

def test_get_order_status(svc, sample_items):
    """REQ-011: get_order_status returns correct status for existing order."""
    order = svc.place_order("USER-001", sample_items)
    status = svc.get_order_status(order.order_id)
    assert status == OrderStatus.PENDING


def test_get_order_status_not_found(svc):
    """REQ-011: get_order_status returns None for unknown order."""
    assert svc.get_order_status("ORD-UNKNOWN") is None


# ── REQ-012: Order History ───────────────────────────────────────────────────

def test_get_order_history_returns_list(svc, sample_items):
    """REQ-012: Order history returns list of orders for the user."""
    svc.place_order("USER-001", sample_items)
    svc.place_order("USER-001", sample_items)
    svc.place_order("USER-002", sample_items)
    history = svc.get_order_history("USER-001")
    assert len(history) == 2
    assert all(o.user_id == "USER-001" for o in history)


# ── REQ-013: Order Cancellation ──────────────────────────────────────────────

def test_cancel_order_success(svc, sample_items):
    """REQ-013: Cancelling a PENDING order sets status to CANCELLED."""
    order = svc.place_order("USER-001", sample_items)
    cancelled = svc.cancel_order(order.order_id)
    assert cancelled.status == OrderStatus.CANCELLED


def test_cancel_order_sets_refund_amount(svc, sample_items):
    """REQ-013: Cancelled order records refund_amount equal to total."""
    order = svc.place_order("USER-001", sample_items)
    cancelled = svc.cancel_order(order.order_id)
    assert cancelled.refund_amount == order.total_amount


def test_cancel_order_invalid_status(svc, sample_items):
    """REQ-013: Cannot cancel a SHIPPED order — must raise ValueError."""
    order = svc.place_order("USER-001", sample_items)
    svc.update_shipping(order.order_id, "TRACK-123")
    with pytest.raises(ValueError):
        svc.cancel_order(order.order_id)


# ── REQ-016: Shipping Update ─────────────────────────────────────────────────

def test_update_shipping_status(svc, sample_items):
    """REQ-016: update_shipping sets status to SHIPPED and records tracking number."""
    order = svc.place_order("USER-001", sample_items)
    shipped = svc.update_shipping(order.order_id, "TRACK-XYZ789")
    assert shipped.status == OrderStatus.SHIPPED
    assert shipped.tracking_number == "TRACK-XYZ789"


# ── REQ-019: Return Request ──────────────────────────────────────────────────

def test_request_return_within_window(svc, sample_items):
    """REQ-019: Return request on a DELIVERED order returns a return_id."""
    order = svc.place_order("USER-001", sample_items)
    order.status = OrderStatus.DELIVERED
    svc._orders[order.order_id] = order
    result = svc.request_return(order.order_id, "Item damaged")
    assert result["success"] is True
    assert result["return_id"].startswith("RET-")
